export const USERS = {
  STANDARD_USER: {
    email: 'xaxaxax@gmail.com',
    password: '11111',
    securityAnswer: 'hi'
  },
  DYNAMIC_USER: () => ({
    email: `testuser_${Date.now()}@gmail.com`,
    password: 'StaticPassword123!',
    securityAnswer: 'AutoGenerated'
  })
};